version : '3.8'
services:
  db:
    image: mysql:5.7
    container_name: payhere
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payhere
    ports:
      - "33066:3306"

  backend:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

