# Generated by Django 4.0.1 on 2022-01-10 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('P001', '현금'), ('P002', '은행'), ('P003', '신용카드'), ('P004', '체크카드')], max_length=10)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C001', '식비'), ('C002', '교통비'), ('C003', '문화생활'), ('C004', '마트/편의점'), ('C005', '쇼핑'), ('C006', '건강'), ('C007', '교육'), ('C008', '기타')], max_length=10)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(choices=[(1, '수입'), (2, '지출')], default='지출')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amout', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_category', to='accountBook.category')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_payment', to='accountBook.payment')),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
