# Generated by Django 4.0.1 on 2022-01-08 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(10, 'Cash'), (12, 'Credit Card'), (13, 'Debit Card'), (11, 'Bank')])),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accountBook.category')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accountBook.payment')),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
