# Generated by Django 4.0.1 on 2022-01-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountBook', '0003_alter_payment_options_alter_account_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='group',
            new_name='type',
        ),
    ]
