# Generated by Django 4.0.1 on 2022-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountBook', '0004_rename_group_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.CharField(choices=[('CASH', '현금'), ('BANK', '은행'), ('CREDIT', '신용카드'), ('DEBIT', '체크카드')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
