# Generated by Django 4.0.1 on 2022-01-10 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountBook', '0005_alter_payment_group_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amout',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
